from pathlib import Path

from PIL import ImageFont

MAIN_PATH = Path(__file__).parent

VENERA_75 = ImageFont.truetype(str(MAIN_PATH / "Venera.otf"), 75)
EXTRA_30 = ImageFont.truetype(str(MAIN_PATH / "Extra.otf"), 30)
Harmony_Sans_Bold_15 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 15)
Harmony_Sans_Bold_20 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 20)
Harmony_Sans_Bold_25 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 25)
Harmony_Sans_Bold_30 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 30)
Harmony_Sans_Bold_35 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 35)
Harmony_Sans_Bold_40 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 40)
Harmony_Sans_Bold_45 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 45)
Harmony_Sans_Bold_50 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 50)
Harmony_Sans_Bold_55 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 55)
Harmony_Sans_Bold_60 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 60)
Harmony_Sans_Bold_65 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 65)
Harmony_Sans_Bold_70 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 70)
Harmony_Sans_Bold_75 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 75)
Harmony_Sans_Bold_80 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Bold.ttf"), 80)
Harmony_Sans_Light_15 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 15)
Harmony_Sans_Light_20 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 20)
Harmony_Sans_Light_25 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 25)
Harmony_Sans_Light_30 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 30)
Harmony_Sans_Light_35 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 35)
Harmony_Sans_Light_40 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 40)
Harmony_Sans_Light_45 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 45)
Harmony_Sans_Light_50 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 50)
Harmony_Sans_Light_55 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 55)
Harmony_Sans_Light_60 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 60)
Harmony_Sans_Light_65 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 65)
Harmony_Sans_Light_70 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 70)
Harmony_Sans_Light_75 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 75)
Harmony_Sans_Light_80 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Light.ttf"), 80)
Harmony_Sans_Reg_15 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 15)
Harmony_Sans_Reg_20 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 20)
Harmony_Sans_Reg_25 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 25)
Harmony_Sans_Reg_30 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 30)
Harmony_Sans_Reg_35 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 35)
Harmony_Sans_Reg_40 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 40)
Harmony_Sans_Reg_45 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 45)
Harmony_Sans_Reg_50 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 50)
Harmony_Sans_Reg_55 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 55)
Harmony_Sans_Reg_60 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 60)
Harmony_Sans_Reg_65 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 65)
Harmony_Sans_Reg_70 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 70)
Harmony_Sans_Reg_75 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 75)
Harmony_Sans_Reg_80 = ImageFont.truetype(str(MAIN_PATH / "HarmonyOS_Sans_SC_Regular.ttf"), 80)
